[build]
  command = "pip install -r requirements.txt && gunicorn app:app"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
